version: "3.9"

services:
  postgres:
    container_name: DAKL_postgreSQL
    image: postgres:15.7
    restart: unless-stopped
    ports:
      - "5440:5432"
    env_file:
      - /root/DAKL/ENV/docker-compose.infrastructure.env
    volumes:
      - ./.docker-data/postgres/data:/var/lib/postgresql/data
    networks:
      - main-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M

  redis:
    container_name: redis_typeorm_basesource
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./.docker-data/redis/data/redis:/data
      - ./docker-data/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    networks:
      - main-network
    env_file: /root/DAKL/ENV/docker-compose.infrastructure.env
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 600M
    restart: unless-stopped

  minio-service:
    container_name: minio_dakl
    image: minio/minio:latest
    volumes:
      - ./.docker-data/minio/data:/data
    ports:
      - "9000:9000"
      - "9099:9099"
    env_file:
      - /root/DAKL/ENV/docker-compose.infrastructure.env
    command: server --address ":9099" --console-address ":9000" /data
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M

  zookeeper-trigger-strategy:
    image: zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka-trigger-strategy:
    image: bitnami/kafka:3.4
    restart: always
    links:
      - zookeeper-trigger-strategy
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-trigger-strategy:2181
    ports:
      - "9092:9092"

  kafka-ui-trigger-strategy:
    image: provectuslabs/kafka-ui:latest
    restart: always
    ports:
      - "8080:8080"
    links:
      - kafka-trigger-strategy
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
    volumes:
      - ./.docker-data/kafka-ui/config:/etc/kafkaui
networks:
  main-network:
    driver: bridge
