version: "3.9"

services:
  postgres:
    container_name: DAKL_postgreSQL
    image: postgres:15.7
    restart: unless-stopped
    ports:
      - "5440:5432"
    env_file:
      - /root/DAKL/ENV/docker-compose.infrastructure.env
    volumes:
      - ./.docker-data/postgres/data:/var/lib/postgresql/data
    networks:
      - main-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M

  redis:
    container_name: redis_typeorm_basesource
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./.docker-data/redis/data/redis:/data
      - ./docker-data/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    networks:
      - main-network
    env_file: /root/DAKL/ENV/docker-compose.infratructure.env
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 600M
    restart: unless-stopped
networks:
  main-network:
    driver: bridge
