export const Permissions = {
  QUAN_LY_ADMIN: 'QUAN_LY_ADMIN',
  DANG_KY_LAM_GIA_SU: 'DANG_KY_LAM_GIA_SU',
  REPLY_MESSAGE: 'REPLY_MESSAGE',
  SEND_MESSAGE: 'SEND_MESSAGE',
  QUAN_LY_BAI_DANG: 'QUAN_LY_BAI_DANG',
  QUAN_LY_NGUOI_DUNG: 'QUAN_LY_NGUOI_DUNG',
  QUAN_LY_YEU_CAU: 'QUAN_LY_YEU_CAU'
};
